### ISSUE TITLE
Is there any plan about pinia?

### ISSUE THREAD

**Issue by skimhugo** [vuex-orm/vuex-orm-next#113]
Is there any plan about pinia?

**Comment by cuebit** [comment]
No concrete plan as of yet. But this is a hot topic for obvious reasons.

**Comment by CodeDredd** [comment]
Plan made and executed. Took me some time but started a working version of vuex-orm for pinia
@skimmilk6877 ~~https://github.com/storm-tail/pinia-orm~~  moved to https://github.com/CodeDredd/pinia-orm
Feedback welcome 😃

**Comment by idc77** [comment]
quasar(.dev) now claims vuex has been deprecated by the vue team.
```
◉   ESLint - recommended
◯   State Management (Pinia)
◯   State Management (Vuex) [DEPRECATED by Vue Team]
◯   Axios
◯   Vue-i18n
```
and has this link: https://vuejs.org/guide/scaling-up/state-management.html#pinia
Seems like everyone has gone crazy about TS. I'm not a fan, being a former Angular dev.
OTOH if Angular had such a nice orm as this library I wouldn't had changed despite the horrible rxjs.
But I digress.

@CodeDredd If you're moving / transforming vuex-orm, you shouldn't forget the plugins, esp axios.
But I hope vuex-orm will transform to pinia-orm. I mean I'm fine with vuex personally, don't really care about pinia or vuex or whatever other state mgmt lib as long as I can view what's going on with the devtools and have a http client that takes care of response to entity translation.

**Comment by CodeDredd** [comment]
@idc77 ok i try to move the plugins if needed. so i try to start with axios.

**Comment by TomiPBass** [comment]
@CodeDredd is there any progress on the axios plugin for pinia-orm?
