### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by Super-Chama** [vuex-orm/vuex-orm-next#137]
I've been searching for a data layer separation for vue and came across vue orm. it's a neat little library but looks like haven't received any updates in over 2 years.. is this project abandoned? do we have a perhaps better solution?

**Comment by Pok09** [comment]
Use this [Pinia-ORM](https://pinia-orm.coded)

**Comment by thopiddock** [comment]
Now found here:
https://pinia-orm.codedredd.de/
https://github.com/codedredd/pinia-orm
