### ISSUE TITLE
Installation docs install 0.36.3 version

### ISSUE THREAD

**Issue by abraxxa** [vuex-orm/vuex-orm-next#46]
The command in the [Installation](https://next.vuex-orm.org/guide/prologue/installation.html#package-manager) docs installs version 0.36.3 instead of the current 1.0 beta version.

#### Steps to reproduce the bug

run `npm install @vuex-orm/core --save`

#### Expected behaviour

Version 1.0 draft 8 installed.

**Comment by cuebit** [comment]
Oh dear 🤦 thanks a million for pointing this out! 👍

**Comment by cuebit** [comment]
Updated!
