### ISSUE TITLE
vue3 / vuex4

### ISSUE THREAD

**Issue by w4mike** [vuex-orm/vuex-orm-next#54]
Hi there,

nice to see how the project developed.

Just one question:
is it already made for vue3 / vuex4 ?
Planning to use it with quasar2.

Many thanks.
Mike

**Comment by cuebit** [comment]
Yes, Vuex ORM supports Vuex 4. Vuex 3/4 are only inherently different in supporting the underlying functionality offered by Vue 2/3 respectively. Since Vuex ORM's functionality is built atop Vuex, and Vuex 4 API is unchanged, it is therefore unaffected. 👍

**Comment by nise** [comment]
Ahm, could you provide an example? The import is not working as mentioned in the docs.

**Comment by nise** [comment]
What is the right way to import vuex-orm? I tried to import the model:

```
import { Model } from '@vuex-orm/core'
import { VuexORM } from '@vuex-orm/core'

const database = VuexORM.Database()

```

I get errors like

"export 'VuexORM' was not found in '@vuex-orm/core'


Versions:
```
"vue": "3.2.29",
    "vue-router": "^4.0.1",
    "vuex": "4.0.0-rc.2",
    "vuex-orm": "^0.36.4"
```
