### ISSUE TITLE
Inserting Data With Default Values

### ISSUE THREAD

**Issue by Zenthae** [vuex-orm/vuex-orm-next#57]
https://next.vuex-orm.org/guide/repository/inserting-data.html#inserting-data-with-default-values

> The new method will create a record with all fields filled with default values defined in the model.
> ```js
> const user = store.$repo(User).new()
> 
> // { id: '$uid1', name: '' }
> ```

that's what's written on the doc, but the `new()` method doesn't exist in practice ? so how i'm supposed to add data ?

`this.$store.$repo(User).insert(new User());` ? that's what i'm using at the moment, but i'm not sure if it's the right way to do it

**Comment by cuebit** [comment]
Ah yea, this was replaced with `$repo(User).make()`

Docs need updating! Thanks for spotting this.

**Comment by Zenthae** [comment]
@cuebit you haven't told me what should i use to do the same though. is there a way ?

**Comment by kiaking** [comment]
@Zenthae It might not be suitable solution but you must at least give 1 default field value. Like `insert({ name: '' })`.

Or should we create a record if users pass in an empty object 🤔 ?

**Comment by cuebit** [comment]
Sorry, I was meant to respond to this but found a bug where `add` was actually doing exactly what @Zenthae was asking about when it shouldn't of been! That's been resolved by #58 since. 

@kiaking this needs to be implemented right? I don't think a query method currently exists to support this.

**Comment by kiaking** [comment]
@cuebit Yap it should! But, just wondering if it might make sense to actually create a new record when passing in empty object `{}`. It does the same thing as `new` method, but, it might make sense.

Either way I think having `new` method make sense as an API. Easier to understand so 👀

**Comment by cuebit** [comment]
True. But then there has to be the `uid` attribute caveat for all the persist methods 😂 maybe `new` is a safe bet.

**Comment by kiaking** [comment]
Ah very good point. Yeah lets go with `new` method only for now 😆

**Comment by Zenthae** [comment]
any news on this ?

**Comment by cuebit** [comment]
Should have a PR by the end of the week 👍

**Comment by Zenthae** [comment]
👋
