### ISSUE TITLE
Error in code example on docs for one-to-many inverse relationship

### ISSUE THREAD

**Issue by M3psipax** [vuex-orm/vuex-orm-next#82]
#### Describe the bug

See line https://github.com/vuex-orm/vuex-orm-next/blame/master/docs/guide/relationships/one-to-many.md#L67 .

The relationship is defined to belong to a `Post` with an `id` equal to `userId`, but `Comment` has no `userId`. I think it should be `postId` instead.

**Comment by cuebit** [comment]
Got time for a PR? 🙏

**Comment by M3psipax** [comment]
here you go: https://github.com/vuex-orm/vuex-orm-next/pull/83

**Comment by cuebit** [comment]
That was so quick 😂 thanks!

**Comment by M3psipax** [comment]
small change :)
